language: php

sudo: false

php:
  - 5.5
  - 5.6
  - 7.0
  - hhvm

matrix:
  allow_failures:
    - php: hhvm

services:
  - redis-server

before_install:
  - if [[ ! $TRAVIS_PHP_VERSION = hhvm* ]]; then echo "extension = redis.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini; fi;

install:
  - travis_retry composer install --no-interaction --prefer-source

before_script:
  - travis_retry wget https://scrutinizer-ci.com/ocular.phar

script:
  - vendor/bin/phpunit --config=phpunit-coverage.xml --coverage-clover=coverage.xml
  - vendor/bin/phpcs --standard=PSR2 src

after_script:
  - php ocular.phar code-coverage:upload --format=php-clover coverage.xml
